services:
  spongout:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spongout
    image: pmackiewicz6/spongout-image:latest
    ports:
      - "8080:8080"
    restart: unless-stopped