spring:
  application:
    name: SpongOut

app:
  config:
    game:
      min-players-to-start: 2
      max-players-in-lobby: 5
      countdown-seconds: 5
      round-max-seconds: 20
      arena-initial-radius: 500.0
      player-starting-mass: 1.0

# Add logging configuration for WebSocket/STOMP debugging
logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        messaging.simp: TRACE
        web:
          socket: DEBUG
          socket.messaging: TRACE