spring:
  application:
    name: SpongOut

app:
  config:
    game:
      min-players-to-start: 2
      max-players-in-lobby: 5
      countdown-seconds: 5
      round-max-seconds: 20
      arena-initial-radius: 500.0