spring:
  application:
    name: SpongOut

app:
  config:
    game:
      min-players-to-start: 2
      max-players-in-lobby: 5
      countdown-seconds: 5
      round-max-seconds: 20
      arena-initial-radius: 500.0
      player-starting-mass: 1.0

# Add logging configuration for WebSocket/STOMP debugging
logging:
  level:
    # Enable STOMP protocol debug logs
    org.springframework.messaging: DEBUG
    # Enable WebSocket connection debug logs
    org.springframework.web.socket: DEBUG
    # Enable message broker logs
    org.springframework.messaging.simp: DEBUG
    # Enable STOMP message handling logs
    org.springframework.messaging.simp.stomp: DEBUG
    # Enable WebSocket transport logs
    org.springframework.web.socket.messaging: DEBUG
    # Enable session management logs
    org.springframework.messaging.simp.user: DEBUG