spring:
  application:
    name: SpongOut

app:
  config:
    game:
      min-players-to-start: 2
      max-players-in-lobby: 5
      countdown-seconds: 5
      round-max-seconds: 20
      arena-initial-radius: 500.0
      player-starting-size: 10.0
      tick-rate-ms: 16 # 16 = about 60fps (1000/60)

      player-growth-rate: 3.0 # Mass per second
      player-spin-rate-rad: 6 # Math.PI * 2 (Radians per second, 1 full rotation)
      friction-factor: 0.98 # Multiplier per frame
      sudden-death-ms: 5000 # 30 seconds
      arena-shrink-rate: 10.0 # Radius units per second
      launch-power-multiplier: 15

# Add logging configuration for WebSocket/STOMP debugging
logging:
  level:
    com.spongout.spongout: DEBUG
    org:
      springframework:
        messaging: INFO
        web:
          socket: INFO